fail_fast: false
exclude: ^(.*/)?(migrations|\.venv)(/.*)?$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: []

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--strict", "--ignore-missing-imports"]
